local Config = {
    DEBUG=true,
    CHAOS={ PERIOD_SEC=60, MAX_SIMULTANEOUS=2, DURATION_SEC=20, TELEGRAPH_SEC=3 },
    WAVES={ START_COUNT=10, GROWTH=1.25 },
    REWARDS={ COIN_PER_WAVE=5, SURVIVE_MIN_BONUS={ [5]=20,[10]=50 } }
}
return Config
